apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: btcd-app-mainnet-cluster-service
  labels:
    app: btcd-app-mainnet-cluster
spec:
  ports:
    # Accept traffic sent to port 18333
    - name: btcd-mainnet-sset
      port: 8333
      targetPort: 8333
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: btcd-app-mainnet-cluster
  type: LoadBalancer    
