apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: btcd-sset
spec:
  serviceName: "btcd-app-cluster-service"
  replicas: 3
  selector:
    matchLabels:
      app: btcd-app-mainnet-cluster
  template:
    metadata:
      labels:
        app: btcd-app-mainnet-cluster
    spec:
      containers:
      - name: btcd-app-mainnet-cluster
        image: vallywal/btcd-mainnet-cluster:v3
        ports:
        - containerPort: 8333
          name: btcd-sset
        volumeMounts:
        - name: btcd-app-mainnet-cluster-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: btcd-app-mainnet-cluster-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Gi
---
apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: btcd-app-mainnet-cluster-service
  labels:
    app: btcd-app-mainnet-cluster
spec:
  ports:
    # Accept traffic sent to port 8333
    - name: btcd-sset
      port: 8333
      targetPort: 8333
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: btcd-app-mainnet-cluster
  type: LoadBalancer    
